from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Grade_Average(object):
    def setupUi(self, Grade_Average):
        Grade_Average.setObjectName("Grade_Average")
        Grade_Average.resize(292, 347)
        Grade_Average.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=Grade_Average)
        self.centralwidget.setObjectName("centralwidget")
        self.header_grades_average_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.header_grades_average_label.setGeometry(QtCore.QRect(70, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.header_grades_average_label.setFont(font)
        self.header_grades_average_label.setObjectName("header_grades_average_label")
        self.button_Submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_Submit.setGeometry(QtCore.QRect(90, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_Submit.setFont(font)
        self.button_Submit.setObjectName("button_Submit")
        self.label_student_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_student_name.setGeometry(QtCore.QRect(40, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_student_name.setFont(font)
        self.label_student_name.setObjectName("label_student_name")
        self.label_student_name_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_student_name_2.setGeometry(QtCore.QRect(10, 90, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_student_name_2.setFont(font)
        self.label_student_name_2.setObjectName("label_student_name_2")
        self.label_Score_One = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Score_One.setGeometry(QtCore.QRect(60, 130, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Score_One.setFont(font)
        self.label_Score_One.setObjectName("label_Score_One")
        self.label_Score_Two = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Score_Two.setGeometry(QtCore.QRect(60, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Score_Two.setFont(font)
        self.label_Score_Two.setObjectName("label_Score_Two")
        self.label_Score_Three = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Score_Three.setGeometry(QtCore.QRect(60, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Score_Three.setFont(font)
        self.label_Score_Three.setObjectName("label_Score_Three")
        self.label_Score_Four = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Score_Four.setGeometry(QtCore.QRect(60, 220, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Score_Four.setFont(font)
        self.label_Score_Four.setObjectName("label_Score_Four")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 110, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_Feedback = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Feedback.setGeometry(QtCore.QRect(120, 290, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Feedback.setFont(font)
        self.label_Feedback.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_Feedback.setObjectName("label_Feedback")
        self.line_Score_One = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_Score_One.setGeometry(QtCore.QRect(130, 130, 61, 20))
        self.line_Score_One.setObjectName("line_Score_One")
        self.line_Score_Two = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_Score_Two.setGeometry(QtCore.QRect(130, 160, 61, 20))
        self.line_Score_Two.setObjectName("line_Score_Two")
        self.line_Score_Three = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_Score_Three.setGeometry(QtCore.QRect(130, 190, 61, 20))
        self.line_Score_Three.setObjectName("line_Score_Three")
        self.line_Score_Four = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_Score_Four.setGeometry(QtCore.QRect(130, 220, 61, 20))
        self.line_Score_Four.setObjectName("line_Score_Four")
        self.line_Student_Name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_Student_Name.setGeometry(QtCore.QRect(130, 60, 131, 20))
        self.line_Student_Name.setObjectName("line_Student_Name")
        self.line_Number_Attempts = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_Number_Attempts.setGeometry(QtCore.QRect(130, 90, 131, 20))
        self.line_Number_Attempts.setObjectName("line_Number_Attempts")
        Grade_Average.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Grade_Average)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 292, 18))
        self.menubar.setObjectName("menubar")
        Grade_Average.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Grade_Average)
        self.statusbar.setObjectName("statusbar")
        Grade_Average.setStatusBar(self.statusbar)

        self.retranslateUi(Grade_Average)
        QtCore.QMetaObject.connectSlotsByName(Grade_Average)

    def retranslateUi(self, Grade_Average):
        _translate = QtCore.QCoreApplication.translate
        Grade_Average.setWindowTitle(_translate("Grade_Average", "MainWindow"))
        self.header_grades_average_label.setText(_translate("Grade_Average", "Grade Average"))
        self.button_Submit.setText(_translate("Grade_Average", "Submit"))
        self.label_student_name.setText(_translate("Grade_Average", "Student Name:"))
        self.label_student_name_2.setText(_translate("Grade_Average", "Number of Attempts:"))
        self.label_Score_One.setText(_translate("Grade_Average", "Score one:"))
        self.label_Score_Two.setText(_translate("Grade_Average", "Score two:"))
        self.label_Score_Three.setText(_translate("Grade_Average", "Score three:"))
        self.label_Score_Four.setText(_translate("Grade_Average", "Score four:"))
        self.label_Feedback.setText(_translate("Grade_Average", "xxxx"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Grade_Average = QtWidgets.QMainWindow()
    ui = Ui_Grade_Average()
    ui.setupUi(Grade_Average)
    Grade_Average.show()
    sys.exit(app.exec())
